"use client";
import {ChangeEvent,FormEvent,useEffect,useMemo,useState} from "react";
type Stage="Saved"|"Applied"|"No response after application"|"Phone screen"|"Interview"|"No response after interview"|"Assessment"|"Offer"|"Rejected";
type App={id:number;company:string;role:string;sector:string;stage:Stage;date:string;location:string;url:string;description:string;phoneDate?:string;phoneTime?:string;interviewDate?:string;interviewTime?:string;eventDate?:string;eventTime?:string};
type ScheduledEvent={application:App;kind:"Phone call"|"Interview";date:string;time?:string};
type Profile={name:string;headline:string;phone:string;email:string;address:string;linkedin:string;summary:string;skills:string;experience:string;education:string;certifications:string[]};
type ResumeFile={name:string;size:number;type:string;dataUrl:string;uploadedAt:string};
const defaultProfile:Profile={name:"Tobi Monilari",headline:"IT Support & Cloud Engineer",phone:"+1 343 987 1884",email:"tobimonilari@gmail.com",address:"Ottawa, Canada",linkedin:"",summary:"IT professional with over 8 years of experience in Identity & Access Management, Microsoft 365 administration, cloud solutions, endpoint management, and enterprise technical support.",skills:"Identity & Access Management, Active Directory, Microsoft Entra ID, Microsoft 365, Exchange Online, Teams, SharePoint, Intune, KACE, Jamf, Microsoft Azure, Conditional Access, MFA, Jira, ServiceNow, Technical Support",experience:"IT Support Engineer — Service Management Group | Jul 2022–Present\nTechnical Support Representative — Voxloud | Jun 2021–Jul 2022\nSupport Agent — Crossover for Work | Jul 2019–Feb 2021\nCloud Support Engineer — Tek Experts | Apr 2018–Jul 2019\nInformation Technology Officer — Marine Platform Limited | Dec 2015–Mar 2018",education:"Master’s in Information Technology | 2016–2018\nB.Sc. (Hons), Pure and Applied Mathematics | 2008–2014",certifications:["Microsoft 365 Certified: Administrator Expert","Microsoft Certified: Identity and Access Administrator Associate","Microsoft Certified: Azure Fundamentals"]};
const seed:App[]=[
{id:1,company:"Northstar Health",role:"Cloud Support Engineer",sector:"Health tech",stage:"Interview",date:"2026-08-18",location:"Ottawa · Hybrid",url:"",description:"Azure cloud support, identity administration and customer troubleshooting."},
{id:2,company:"Maple Finance",role:"IAM Analyst",sector:"Financial services",stage:"Phone screen",date:"2026-08-16",location:"Toronto · Remote",url:"",description:"Identity governance, access reviews, Entra ID and conditional access."},
{id:3,company:"BrightDesk",role:"Senior IT Support Specialist",sector:"SaaS",stage:"Applied",date:"2026-08-14",location:"Remote",url:"",description:"Microsoft 365, Intune and tier 2 support for a distributed team."},
{id:4,company:"Civic Cloud",role:"Microsoft 365 Administrator",sector:"Public sector",stage:"Assessment",date:"2026-08-11",location:"Ottawa",url:"",description:"Microsoft 365 tenant administration, endpoint security and compliance."},
{id:5,company:"Harbour Systems",role:"Technical Support Engineer",sector:"IT services",stage:"Rejected",date:"2026-08-05",location:"Canada · Remote",url:"",description:"Customer-facing technical support and incident resolution."}];
const stages:Stage[]=["Saved","Applied","No response after application","Phone screen","Interview","No response after interview","Assessment","Offer","Rejected"];
const tone:Record<Stage,string>={Saved:"slate",Applied:"blue","No response after application":"waiting","Phone screen":"amber",Interview:"purple","No response after interview":"waiting",Assessment:"cyan",Offer:"green",Rejected:"red"};
export default function Home(){
 const[apps,setApps]=useState<App[]>(seed),[view,setView]=useState<"overview"|"applications"|"prepare"|"profile">("overview"),[modal,setModal]=useState(false),[selected,setSelected]=useState<App|null>(seed[0]),[query,setQuery]=useState(""),[profile,setProfile]=useState<Profile>(defaultProfile),[resume,setResume]=useState<ResumeFile|null>(null),[saved,setSaved]=useState(false);
 useEffect(()=>{const x=localStorage.getItem("careerflow-applications");if(x){const saved:App[]=JSON.parse(x);setApps(saved.map(a=>({...a,phoneDate:a.phoneDate||(a.stage==="Phone screen"?a.eventDate:undefined),phoneTime:a.phoneTime||(a.stage==="Phone screen"?a.eventTime:undefined),interviewDate:a.interviewDate||(a.stage==="Interview"?a.eventDate:undefined),interviewTime:a.interviewTime||(a.stage==="Interview"?a.eventTime:undefined)})))}} ,[]);useEffect(()=>localStorage.setItem("careerflow-applications",JSON.stringify(apps)),[apps]);
 useEffect(()=>{const p=localStorage.getItem("appliflow-profile"),r=localStorage.getItem("appliflow-resume");if(p)setProfile(JSON.parse(p));if(r)setResume(JSON.parse(r))},[]);
 const active=apps.filter(a=>!["Rejected","Offer"].includes(a.stage)).length,interviews=apps.filter(a=>a.stage==="Interview").length,offers=apps.filter(a=>a.stage==="Offer").length,response=apps.length?Math.round(apps.filter(a=>!["Saved","Applied","No response after application"].includes(a.stage)).length/apps.length*100):0;
 const filtered=useMemo(()=>apps.filter(a=>`${a.company} ${a.role} ${a.sector}`.toLowerCase().includes(query.toLowerCase())),[apps,query]);
 const nextEvent=useMemo<ScheduledEvent|undefined>(()=>{const events:ScheduledEvent[]=[];const today=new Date().toISOString().slice(0,10);apps.forEach(a=>{if(a.phoneDate&&a.phoneDate>=today)events.push({application:a,kind:"Phone call",date:a.phoneDate,time:a.phoneTime});if(a.interviewDate&&a.interviewDate>=today)events.push({application:a,kind:"Interview",date:a.interviewDate,time:a.interviewTime})});return events.sort((a,b)=>`${a.date}T${a.time||"23:59"}`.localeCompare(`${b.date}T${b.time||"23:59"}`))[0]},[apps]);
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),n:App={id:Date.now(),company:String(f.get("company")),role:String(f.get("role")),sector:String(f.get("sector")),stage:"Saved",date:String(f.get("applicationDate")||new Date().toISOString().slice(0,10)),location:String(f.get("location")),url:String(f.get("url")),description:String(f.get("description"))};setApps([n,...apps]);setSelected(n);setModal(false);setView("prepare")}
 function update(id:number,stage:Stage){setApps(apps.map(a=>a.id===id?{...a,stage}:a));setSelected(s=>s?.id===id?{...s,stage}:s)}
 function editDate(id:number,field:"date"|"phoneDate"|"phoneTime"|"interviewDate"|"interviewTime",value:string){setApps(apps.map(a=>a.id===id?{...a,[field]:value}:a));setSelected(s=>s?.id===id?{...s,[field]:value}:s)}
 function remove(application:App){if(!window.confirm(`Delete ${application.role} at ${application.company}? This cannot be undone.`))return;const remaining=apps.filter(a=>a.id!==application.id);setApps(remaining);if(selected?.id===application.id)setSelected(remaining[0]??null)}
 function saveProfile(){localStorage.setItem("appliflow-profile",JSON.stringify(profile));setSaved(true);window.setTimeout(()=>setSaved(false),1800)}
 function uploadResume(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>3*1024*1024){window.alert("Please choose a resume smaller than 3 MB.");e.target.value="";return}const reader=new FileReader();reader.onload=()=>{const item:ResumeFile={name:file.name,size:file.size,type:file.type,dataUrl:String(reader.result),uploadedAt:new Date().toISOString()};try{localStorage.setItem("appliflow-resume",JSON.stringify(item));setResume(item)}catch{window.alert("This file could not be saved in browser storage. Try a smaller PDF or Word file.")}};reader.readAsDataURL(file)}
 function removeResume(){if(!window.confirm("Remove the uploaded master resume? Your editable profile will remain."))return;localStorage.removeItem("appliflow-resume");setResume(null)}
 return <main><aside><div className="brand"><span className="mark">A</span><div>AppliFlow<small>APPLICATION STUDIO</small></div></div><nav><button className={view==="overview"?"active":""} onClick={()=>setView("overview")}>⌂ <span>Overview</span></button><button className={view==="applications"?"active":""} onClick={()=>setView("applications")}>▣ <span>Applications</span><b>{apps.length}</b></button><button className={view==="prepare"?"active":""} onClick={()=>setView("prepare")}>✦ <span>Prep studio</span></button><button className={view==="profile"?"active":""} onClick={()=>setView("profile")}>▤ <span>Master CV</span></button></nav><div className="profile"><div className="avatar">{initials(profile.name)}</div><div><strong>{profile.name}</strong><small>{profile.headline}</small></div></div></aside>
 <section className="shell"><header className="appheader"><div><p className="eyebrow">THURSDAY, AUGUST 20</p><h1>{view==="overview"?`Good morning, ${profile.name.split(" ")[0]||"there"}`:view==="applications"?"Your applications":view==="prepare"?"Prep studio":"Master CV"}</h1><p>{view==="overview"?"Here’s how your search is moving.":view==="applications"?"Every opportunity, outcome and next step in one place.":view==="prepare"?"Turn each job description into a focused preparation plan.":"Keep your source resume and career profile current."}</p></div>{view!=="profile"&&<button className="primary" onClick={()=>setModal(true)}>＋ New application</button>}</header>
 {view==="overview"&&<><div className="metrics"><Metric label="TOTAL APPLICATIONS" value={apps.length} note="All tracked roles" icon="↗"/><Metric label="ACTIVE PIPELINE" value={active} note="Still in progress" icon="◎"/><Metric label="INTERVIEWS" value={interviews} note="Preparation ready" icon="◫"/><Metric label="RESPONSE RATE" value={`${response}%`} note={`${offers} offers so far`} icon="⌁"/></div><div className="grid"><section className="card pipeline"><Head over="PIPELINE" title="Application stages" action={()=>setView("applications")}/><div className="bars">{stages.slice(1).map(s=>{const n=apps.filter(a=>a.stage===s).length;return <div className="barrow" key={s}><span>{s}</span><div><i className={tone[s]} style={{width:`${Math.max(4,n/Math.max(1,apps.length)*100)}%`}}/></div><strong>{n}</strong></div>})}</div></section><section className="card next"><p className="eyebrow">NEXT UP</p><h2>Stay ready</h2>{nextEvent?<div className="nextitem"><span className="datebox">{new Date(nextEvent.date+"T12:00:00").getDate()}<small>{new Date(nextEvent.date+"T12:00:00").toLocaleDateString("en-CA",{month:"short"}).toUpperCase()}</small></span><div><strong>{nextEvent.kind}</strong><p>{nextEvent.application.company}{nextEvent.time?` · ${formatTime(nextEvent.time)}`:""}</p></div></div>:<div className="nextempty"><strong>No call scheduled yet</strong><p>Set a date and time in Prep Studio.</p></div>}<button className="secondary" onClick={()=>{if(nextEvent)setSelected(nextEvent.application);setView("prepare")}}>Open prep studio</button></section></div><section className="card recent"><Head over="RECENT ACTIVITY" title="Latest applications"/><Table apps={apps.slice(0,4)} select={a=>{setSelected(a);setView("prepare")}} update={update} remove={remove}/></section></>}
 {view==="applications"&&<section className="card full"><div className="toolbar"><input aria-label="Search" placeholder="Search company, role or sector…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{filtered.length} roles</span></div><Table apps={filtered} select={a=>{setSelected(a);setView("prepare")}} update={update} remove={remove}/></section>}
 {view==="prepare"&&<div className="prepgrid"><section className="card chooser"><p className="eyebrow">SELECT AN APPLICATION</p>{apps.map(a=><button key={a.id} className={selected?.id===a.id?"chosen":""} onClick={()=>setSelected(a)}><strong>{a.company}</strong><span>{a.role}</span></button>)}</section><section className="card prep">{selected?<><div className="prephead"><div><span className={`pill ${tone[selected.stage]}`}>{selected.stage}</span><h2>{selected.role}</h2><p>{selected.company} · {selected.location}</p></div><div className="prepcontrols"><select aria-label="Stage" value={selected.stage} onChange={e=>update(selected.id,e.target.value as Stage)}>{stages.map(s=><option key={s}>{s}</option>)}</select><button className="delete-button" onClick={()=>remove(selected)}>Delete application</button></div></div><section className="dates-panel"><div><p className="eyebrow">DATES</p><h3>Application timeline</h3></div><div className="datecards"><article><strong>Application</strong><label>Date applied<input type="date" value={selected.date||""} onChange={e=>editDate(selected.id,"date",e.target.value)}/></label></article><article><strong>Phone call</strong><label>Date<input type="date" value={selected.phoneDate||""} onChange={e=>editDate(selected.id,"phoneDate",e.target.value)}/></label><label>Time<input type="time" value={selected.phoneTime||""} onChange={e=>editDate(selected.id,"phoneTime",e.target.value)}/></label></article><article><strong>Interview</strong><label>Date<input type="date" value={selected.interviewDate||""} onChange={e=>editDate(selected.id,"interviewDate",e.target.value)}/></label><label>Time<input type="time" value={selected.interviewTime||""} onChange={e=>editDate(selected.id,"interviewTime",e.target.value)}/></label></article></div></section><div className="match"><span>CV EVIDENCE MATCH</span><strong>Strong foundation</strong><p>Your 8+ years in IAM, Microsoft 365, Azure AD/Entra ID, Intune and enterprise support are the core evidence for this role.</p></div><div className="actions"><Action title="Tailor my CV" text="Create an ATS-friendly CV using only verified experience." icon="▤"/><Action title="Write cover letter" text="Connect your strongest evidence to this company’s needs." icon="✎"/><Action title="Phone screen brief" text="Build a 60-second introduction, likely questions and talking points." icon="◉"/><Action title="Interview practice" text="Generate STAR stories, technical questions and smart questions to ask." icon="✦"/></div><div className="jobtext"><h3>Job description</h3><p>{selected.description}</p>{selected.url&&<a href={selected.url} target="_blank">Open original job posting ↗</a>}</div></>:<div className="empty">Add an application to begin.</div>}</section></div>}
 {view==="profile"&&<ProfileStudio profile={profile} setProfile={setProfile} resume={resume} uploadResume={uploadResume} removeResume={removeResume} saveProfile={saveProfile} saved={saved}/>} 
 </section>{modal&&<div className="overlay" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={add} onMouseDown={e=>e.stopPropagation()}><div className="modalhead"><div><p className="eyebrow">NEW OPPORTUNITY</p><h2>Add an application</h2></div><button type="button" onClick={()=>setModal(false)}>×</button></div><div className="formgrid"><label>Company<input name="company" required/></label><label>Job title<input name="role" required/></label><label>Sector<input name="sector" placeholder="e.g. Financial services"/></label><label>Location<input name="location" placeholder="e.g. Ottawa · Hybrid"/></label><label>Application date<input name="applicationDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label></div><label>LinkedIn or job URL<input name="url" type="url" placeholder="https://www.linkedin.com/jobs/…"/></label><label>Job description<textarea name="description" required rows={8} placeholder="Paste the complete job description here…"/></label><div className="modalactions"><button type="button" onClick={()=>setModal(false)}>Cancel</button><button className="primary">Save & prepare</button></div></form></div>}</main>}
function Metric(p:{label:string;value:string|number;note:string;icon:string}){return <section className="metric"><div><p className="eyebrow">{p.label}</p><strong>{p.value}</strong><span>{p.note}</span></div><i>{p.icon}</i></section>}
function Head({over,title,action}:{over:string;title:string;action?:()=>void}){return <div className="cardhead"><div><p className="eyebrow">{over}</p><h2>{title}</h2></div>{action&&<button onClick={action}>View all →</button>}</div>}
function Action(p:{title:string;text:string;icon:string}){return <button className="action"><i>{p.icon}</i><div><strong>{p.title}</strong><span>{p.text}</span></div><b>→</b></button>}
function formatTime(value:string){return new Date(`2000-01-01T${value}`).toLocaleTimeString("en-CA",{hour:"numeric",minute:"2-digit"})}
function initials(name:string){return name.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"CV"}
function ProfileStudio({profile,setProfile,resume,uploadResume,removeResume,saveProfile,saved}:{profile:Profile;setProfile:(p:Profile)=>void;resume:ResumeFile|null;uploadResume:(e:ChangeEvent<HTMLInputElement>)=>void;removeResume:()=>void;saveProfile:()=>void;saved:boolean}){
 const set=(field:keyof Omit<Profile,"certifications">,value:string)=>setProfile({...profile,[field]:value});
 const certification=(index:number,value:string)=>setProfile({...profile,certifications:profile.certifications.map((c,i)=>i===index?value:c)});
 return <div className="cvstudio"><section className="cvleft"><section className="card upload-card"><div><p className="eyebrow">SOURCE DOCUMENT</p><h2>Master resume</h2><p>Upload your latest PDF or Word resume. Maximum file size: 3 MB.</p></div>{resume?<div className="file-row"><span className="file-icon">CV</span><div><strong>{resume.name}</strong><small>{Math.ceil(resume.size/1024)} KB · Uploaded {new Date(resume.uploadedAt).toLocaleDateString("en-CA")}</small></div><a href={resume.dataUrl} target="_blank" rel="noreferrer">View</a><button onClick={removeResume}>Remove</button></div>:<label className="upload-zone">＋ Choose resume<input type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={uploadResume}/><small>PDF, DOC or DOCX</small></label>}</section>
 <section className="card profile-editor"><div className="editor-head"><div><p className="eyebrow">EDITABLE MASTER PROFILE</p><h2>Career details</h2></div><button className="primary" onClick={saveProfile}>{saved?"Saved ✓":"Save changes"}</button></div><div className="profile-form"><label>Full name<input value={profile.name} onChange={e=>set("name",e.target.value)}/></label><label>Professional headline<input value={profile.headline} onChange={e=>set("headline",e.target.value)}/></label><label>Phone number<input type="tel" value={profile.phone} onChange={e=>set("phone",e.target.value)}/></label><label>Email address<input type="email" value={profile.email} onChange={e=>set("email",e.target.value)}/></label><label>Home address<input value={profile.address} onChange={e=>set("address",e.target.value)}/></label><label>LinkedIn URL<input type="url" placeholder="https://www.linkedin.com/in/…" value={profile.linkedin} onChange={e=>set("linkedin",e.target.value)}/></label><label className="wide">Professional summary<textarea rows={5} value={profile.summary} onChange={e=>set("summary",e.target.value)}/></label><label className="wide">Skills <small>Separate with commas or new lines</small><textarea rows={4} value={profile.skills} onChange={e=>set("skills",e.target.value)}/></label><label className="wide">Experience<textarea rows={7} value={profile.experience} onChange={e=>set("experience",e.target.value)}/></label><label className="wide">Education<textarea rows={4} value={profile.education} onChange={e=>set("education",e.target.value)}/></label></div><div className="cert-editor"><div className="cert-head"><h3>Certifications</h3><button onClick={()=>setProfile({...profile,certifications:[...profile.certifications,""]})}>＋ Add certification</button></div>{profile.certifications.map((c,i)=><div className="cert-row" key={i}><input aria-label={`Certification ${i+1}`} value={c} onChange={e=>certification(i,e.target.value)}/><button aria-label={`Remove certification ${i+1}`} onClick={()=>setProfile({...profile,certifications:profile.certifications.filter((_,x)=>x!==i)})}>×</button></div>)}</div></section></section>
 <section className="cvright"><div className="preview-actions"><span>LIVE PREVIEW</span><button onClick={()=>window.print()}>Print / Save PDF</button></div><article className="resume-preview"><header><h2>{profile.name||"Your name"}</h2><strong>{profile.headline}</strong><p>{[profile.address,profile.phone,profile.email].filter(Boolean).join("  |  ")}</p>{profile.linkedin&&<p>{profile.linkedin}</p>}</header><CvSection title="Profile"><p>{profile.summary}</p></CvSection><CvSection title="Core skills"><div className="skill-list">{profile.skills.split(/[,\n]/).map(s=>s.trim()).filter(Boolean).map((s,i)=><span key={i}>{s}</span>)}</div></CvSection><CvSection title="Professional experience"><p className="preline">{profile.experience}</p></CvSection><CvSection title="Education"><p className="preline">{profile.education}</p></CvSection><CvSection title="Certifications"><ul>{profile.certifications.filter(Boolean).map((c,i)=><li key={i}>{c}</li>)}</ul></CvSection></article></section></div>
}
function CvSection({title,children}:{title:string;children:React.ReactNode}){return <section><h3>{title}</h3>{children}</section>}
function Table({apps,select,update,remove}:{apps:App[];select:(a:App)=>void;update:(id:number,s:Stage)=>void;remove:(a:App)=>void}){return <div className="table"><div className="tr th"><span>COMPANY</span><span>JOB TITLE</span><span>SECTOR</span><span>STAGE</span><span>APPLIED</span><span/></div>{apps.map(a=><div className="tr" key={a.id}><span><strong>{a.company}</strong></span><span className="jobtitle">{a.role}</span><span>{a.sector}</span><span><select aria-label={`Stage for ${a.company}`} className={`pill ${tone[a.stage]}`} value={a.stage} onChange={e=>update(a.id,e.target.value as Stage)}>{stages.map(s=><option key={s}>{s}</option>)}</select></span><span>{a.date?new Date(a.date+"T12:00:00").toLocaleDateString("en-CA",{month:"short",day:"numeric"}):"—"}</span><span className="rowactions"><button className="delete-icon" aria-label={`Delete ${a.role} at ${a.company}`} onClick={()=>remove(a)}>×</button><button className="arrow" aria-label={`Prepare for ${a.role} at ${a.company}`} onClick={()=>select(a)}>→</button></span></div>)}</div>}
